use core::mem::MaybeUninit;

use crate::sys::ksnp_error;

/// Trait for data processor types found in the etsi-protocol library.
///
/// Types implementing this trait are able to receive and generate raw data to
/// be handed off for some I/O handling, and can generate values based on
/// received data.
pub trait Processor {
    /// Type of the values generated by the input data processing functions.
    type Value<'a>
    where
        Self: 'a;

    /// Returns true iff more data is required for further processing.
    fn want_read(&self) -> bool;

    /// Returns true iff more data is available for writing.
    fn want_write(&self) -> bool;

    /// Reads ingress data.
    ///
    /// Returns the number of bytes read. [`Processor::process_data`] should be
    /// called as soon as possible.
    fn read_data(&mut self, data: &[u8]) -> Result<usize, ksnp_error>;

    /// Writes egress data into the provided buffer.
    ///
    /// Returns the number of bytes written into the buffer.
    fn write_data(&mut self, data: &mut [MaybeUninit<u8>]) -> Result<usize, ksnp_error>;

    /// Processes input data.
    fn next_event(&mut self) -> Result<Self::Value<'_>, ksnp_error>;
}
